### ISSUE TITLE
curveadm compatibility exists on ubuntu 22.04

### ISSUE THREAD

**Issue by Cyber-SiKu** [opencurve/curveadm#133]
There are compatibility issues with curveadm running on 22.04：
```
$ curveadm -u

fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x2 addr=0x7fc3ac490072 pc=0x7fc3a9198a7f]

runtime stack:
runtime.throw({0xe94f77?, 0x0?})
/root/.local/go1.18.3/src/runtime/panic.go:992 +0x71
runtime.sigpanic()
/root/.local/go1.18.3/src/runtime/signal_unix.go:802 +0x3a9

goroutine 15 [syscall]:
runtime.cgocall(0xc47ef0, 0xc000053d98)
/root/.local/go1.18.3/src/runtime/cgocall.go:157 +0x5c fp=0xc000053d70 sp=0xc000053d38 pc=0x4058dc
net._C2func_getaddrinfo(0xc0004bc4a0, 0x0, 0xc00025a2d0, 0xc00048a350)
_cgo_gotypes.go:94 +0x56 fp=0xc000053d98 sp=0xc000053d70 pc=0x6418d6
net.cgoLookupIPCNAME.func1({0xc0004bc4a0, 0x0?, 0xc000053f40?}, 0xc0004e61b0?, 0xc000053f98?)
/root/.local/go1.18.3/src/net/cgo_unix.go:160 +0x9f fp=0xc000053df0 sp=0xc000053d98 pc=0x64317f
net.cgoLookupIPCNAME({0xe70b98, 0x3}, {0xc0004e61b0, 0x1f})
/root/.local/go1.18.3/src/net/cgo_unix.go:160 +0x16d fp=0xc000053f38 sp=0xc000053df0 pc=0x6429ed
net.cgoIPLookup(0xc0001820c0?, {0xe70b98?, 0xc000053fd0?}, {0xc0004e61b0?, 0x0?})
/root/.local/go1.18.3/src/net/cgo_unix.go:217 +0x3b fp=0xc000053fa8 sp=0xc000053f38 pc=0x64323b
net.cgoLookupIP.func1()
/root/.local/go1.18.3/src/net/cgo_unix.go:227 +0x36 fp=0xc000053fe0 sp=0xc000053fa8 pc=0x643676
runtime.goexit()
/root/.local/go1.18.3/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc000053fe8 sp=0xc000053fe0 pc=0x466701
created by net.cgoLookupIP
/root/.local/go1.18.3/src/net/cgo_unix.go:227 +0x12a

goroutine 1 [syscall]:
github.com/mattn/go-sqlite3._Cfunc__sqlite3_step(0x2703d58, 0xc000037220, 0xc000037228)
_cgo_gotypes.go:294 +0x4c
github.com/mattn/go-sqlite3.(*SQLiteStmt).exec.func4(0xc0000dde00?, 0x0?, 0x4?)
/root/.local/go/pkg/mod/github.com/mattn/go-sqlite3@v1.6.0/sqlite3.go:1184 +0x65
github.com/mattn/go-sqlite3.(*SQLiteStmt).exec(0xc0000dde00, {0xfd71a8?, 0xc0001b8020}, {0xc0000b0280?, 0x3?, 0xc0004813a0?})
/root/.local/go/pkg/mod/github.com/mattn/go-sqlite3@v1.6.0/sqlite3.go:1184 +0x1df
github.com/mattn/go-sqlite3.(*SQLiteStmt).ExecContext(0x0?, {0xfd71a8, 0xc0001b8020}, {0xc0000b0140, 0x4, 0x10?})
/root/.local/go/pkg/mod/github.com/mattn/go-sqlite3@v1.6.0/sqlite3_go18.go:68 +0x8d
database/sql.ctxDriverStmtExec({0xfd71a8, 0xc0001b8020}, {0xfd7330, 0xc0000dde00}, {0xc0000b0140?, 0x4, 0x4})
/root/.local/go1.18.3/src/database/sql/ctxutil.go:65 +0xcc
database/sql.resultFromStatement({0xfd71a8, 0xc0001b8020}, {0xfd5e48, 0xc00049a480}, 0xc000080080, {0xc000607df8, 0x4, 0x4})
/root/.local/go1.18.3/src/database/sql/sql.go:2663 +0x145
database/sql.(*Stmt).ExecContext(0xc000468000, {0xfd71a8, 0xc0001b8020}, {0xc000607df8, 0x4, 0x4})
/root/.local/go1.18.3/src/database/sql/sql.go:2636 +0x1fd
database/sql.(*Stmt).Exec(...)
/root/.local/go1.18.3/src/database/sql/sql.go:2651
github.com/opencurve/curveadm/internal/storage.(*Storage).InsertAuditLog(0xe75438?, {0xb?, 0xc000607ee0?, 0x15551c0?}, {0xc000036024?, 0xa?}, {0xc000036f70?, 0xb?}, 0xc000607ef0?)
/root/work/curveadm/internal/storage/storage.go:455 +0x23d
github.com/opencurve/curveadm/cli/cli.(*CurveAdm).PreAudit(0xc0004b86c0, {0xc000056738?, 0x461cbb?, 0x15551c0?}, {0xc0001ac010?, 0x1, 0x1})
/root/work/curveadm/cli/cli/cli.go:484 +0x176
github.com/opencurve/curveadm/cli.Execute()
/root/work/curveadm/cli/curveadm.go:48 +0xe5
main.main()
/root/work/curveadm/cmd/curveadm/main.go:30 +0x17

goroutine 51 [select]:
github.com/kpango/fastime.(*fastime).StartTimerD.func1()
/root/.local/go/pkg/mod/github.com/kpango/fastime@v1.1.4/fastime.go:195 +0x11e
created by github.com/kpango/fastime.(*fastime).StartTimerD
/root/.local/go/pkg/mod/github.com/kpango/fastime@v1.1.4/fastime.go:188 +0x14a

goroutine 7 [select]:
database/sql.(*DB).connectionOpener(0xc000481380, {0xfd7170, 0xc0004a6380})
/root/.local/go1.18.3/src/database/sql/sql.go:1226 +0x8d
created by database/sql.OpenDB
/root/.local/go1.18.3/src/database/sql/sql.go:794 +0x18d

goroutine 14 [select]:
net.cgoLookupIP({0xfd7170, 0xc0004a6580}, {0xe70b98, 0x3}, {0xc0004e61b0, 0x1f})
/root/.local/go1.18.3/src/net/cgo_unix.go:228 +0x1aa
net.(*Resolver).lookupIP(0x1554320, {0xfd7170, 0xc0004a6580}, {0xe70b98, 0x3}, {0xc0004e61b0, 0x1f})
/root/.local/go1.18.3/src/net/lookup_unix.go:96 +0x128
net.glob..func1({0xfd7170?, 0xc0004a6580?}, 0x0?, {0xe70b98?, 0xc000110f84?}, {0xc0004e61b0?, 0xc000110f98?})
/root/.local/go1.18.3/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
/root/.local/go1.18.3/src/net/lookup.go:319 +0x9f
internal/singleflight.(*Group).doCall(0x1554330, 0xc0004b2690, {0xc0004e61e0, 0x23}, 0x0?)
/root/.local/go1.18.3/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
/root/.local/go1.18.3/src/internal/singleflight/singleflight.go:88 +0x2ec

goroutine 13 [select]:
net.(*Resolver).lookupIPAddr(0x1554320, {0xfd71e0?, 0xc00049a8a0}, {0xe70b98, 0x3}, {0xc0004e61b0, 0x1f})
/root/.local/go1.18.3/src/net/lookup.go:325 +0x51b
net.(*Resolver).internetAddrList(0xfd71e0?, {0xfd71e0?, 0xc00049a8a0?}, {0xe70b98, 0x3}, {0xc0004e61b0?, 0x22?})
/root/.local/go1.18.3/src/net/ipsock.go:288 +0x67a
net.(*Resolver).resolveAddrList(0x158c750?, {0xfd71e0, 0xc00049a8a0}, {0xe71068, 0x4}, {0xe70b98?, 0xe55be0?}, {0xc0004e61b0, 0x22}, {0x0, ...})
/root/.local/go1.18.3/src/net/dial.go:221 +0x41b
net.(*Dialer).DialContext(0xc00049a6c0, {0xfd71a8, 0xc0001b8020}, {0xe70b98, 0x3}, {0xc0004e61b0, 0x22})
/root/.local/go1.18.3/src/net/dial.go:406 +0x448
net/http.(*Transport).dial(0xae3ad1?, {0xfd71a8?, 0xc0001b8020?}, {0xe70b98?, 0xc00048a320?}, {0xc0004e61b0?, 0x1?})
/root/.local/go1.18.3/src/net/http/transport.go:1169 +0xda
net/http.(*Transport).dialConn(0xc0004c2780, {0xfd71a8, 0xc0001b8020}, {{}, 0x0, {0xc0004e83c0, 0x4}, {0xc0004e61b0, 0x22}, 0x0})
/root/.local/go1.18.3/src/net/http/transport.go:1607 +0x83f
net/http.(*Transport).dialConnFor(0xabedad?, 0xc0001c29a0)
/root/.local/go1.18.3/src/net/http/transport.go:1449 +0xb0
created by net/http.(*Transport).queueForDial
/root/.local/go1.18.3/src/net/http/transport.go:1418 +0x3d2

goroutine 28 [select]:
net/http.(*Transport).getConn(0xc0004c2780, 0xc0004a6500, {{}, 0x0, {0xc0004e83c0, 0x4}, {0xc0004e61b0, 0x22}, 0x0})
/root/.local/go1.18.3/src/net/http/transport.go:1375 +0x5c6
net/http.(*Transport).roundTrip(0xc0004c2780, 0xc0004de400)
/root/.local/go1.18.3/src/net/http/transport.go:581 +0x76f
net/http.(*Transport).RoundTrip(0x40f325?, 0xfd1d20?)
/root/.local/go1.18.3/src/net/http/roundtrip.go:17 +0x19
net/http.send(0xc0004de400, {0xfd1d20, 0xc0004c2780}, {0xe55be0?, 0xc0001b5801?, 0x0?})
/root/.local/go1.18.3/src/net/http/client.go:252 +0x5d8
net/http.(*Client).send(0xc0004a9f20, 0xc0004de400, {0x0?, 0xe40120?, 0x0?})
/root/.local/go1.18.3/src/net/http/client.go:176 +0x9b
net/http.(*Client).do(0xc0004a9f20, 0xc0004de400)
/root/.local/go1.18.3/src/net/http/client.go:725 +0x8f5
net/http.(*Client).Do(...)
/root/.local/go1.18.3/src/net/http/client.go:593
github.com/go-resty/resty/v2.(*Client).execute(0xc0000001e0, 0xc000487d40)
/root/.local/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/client.go:932 +0x40d
github.com/go-resty/resty/v2.(*Request).Execute(0xc000487d40, {0xe70e9c?, 0x0?}, {0xe9d008, 0x38})
/root/.local/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:758 +0x5e9
github.com/go-resty/resty/v2.(*Request).Head(...)
/root/.local/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:694
github.com/opencurve/curveadm/internal/tools/upgrade.GetLatestVersion({0xe71428, 0x5})
/root/work/curveadm/internal/tools/upgrade/upgrade.go:78 +0x20d
github.com/opencurve/curveadm/cli/cli.(*CurveAdm).detectVersion(0xc0004b86c0)
/root/work/curveadm/cli/cli/cli.go:196 +0x33
created by github.com/opencurve/curveadm/cli/cli.NewCurveAdm
/root/work/curveadm/cli/cli/cli.go:104 +0x39c

goroutine 30 [select]:
github.com/mattn/go-sqlite3.(*SQLiteStmt).exec.func3(0x0?)
/root/.local/go/pkg/mod/github.com/mattn/go-sqlite3@v1.6.0/sqlite3.go:1172 +0x70
created by github.com/mattn/go-sqlite3.(*SQLiteStmt).exec
/root/.local/go/pkg/mod/github.com/mattn/go-sqlite3@v1.6.0/sqlite3.go:1171 +0x1a5
``

**Comment by Cyber-SiKu** [comment]
curveadm precheck report ssh connect failed
```
Check Topology <topology>: [OK]
+ cluster=clusterfs  kind=curvefs [1/1] [OK]

Check SSH Connect <ssh>: [ERROR]
+ host=curvefs  method=privateKey [0/1] [ERROR]

Clean Precheck Environment: [ERROR]
---
Error-Code: 510000
Error-Description: SSH connect failed
Error-Clue: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
How to Solve:
* Website: https://github.com/opencurve/curveadm/wiki/errno5#510000
* Log:****
* WeChat: opencurve_bot
```
log
```
2022-08-26 13:48:34     [ERR]:  (log.go:109):   Connect remote SSH
user: ***
host: ***
port: 22
forwardAgent: false
privateKeyPath: ***
timeoutSec: 10
maxRetries: 3
tries: 3
error: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
It seems this has happened for the ssh client in Ubuntu 22.04. The RSA public-private key pair is considered not safe any more.
[ubuntu-22-04-ssh-the-rsa-key](https://askubuntu.com/questions/1409105/ubuntu-22-04-ssh-the-rsa-key-isnt-working-since-upgrading-from-20-04)

**Comment by tistergit** [comment]
i had the same problem

**Comment by livehl** [comment]
花了一天时间，发现 ubuntu 22.04 上clone 源代码编译可以。其他系统编译后的不行。
推荐大家先直接找个22.04的机器编译后使用。

**Comment by livehl** [comment]
然后新问题来了。ssh 不过去。查了一下，是因为 22.04 禁用了RSA SHA-1 ，要求 RSA SHA-2。
这个问题要去修 引用的库 ghop。

把https://github.com/melbahja/goph 代码拉下来，修改 go.mod 文件，把golang.org/x/的三个库更新到最新。
然后修改curveadm库的go.mod ，
使用repalce 替换goph为本地改过代码的目录。
make 后可以使用啦。
@Wine93  麻烦整理下wiki  或者FAQ 。

**Comment by livehl** [comment]
[curveadm.zip](https://github.com/opencurve/curveadm/files/9481913/curveadm.zip)
这是打包好的，amd64,ubuntu 22.04可用版本

**Comment by Wine93** [comment]
> 然后新问题来了。ssh 不过去。查了一下，是因为 22.04 禁用了RSA SHA-1 ，要求 RSA SHA-2。 这个问题要去修 引用的库 ghop。
> 
> 把https://github.com/melbahja/goph 代码拉下来，修改 go.mod 文件，把golang.org/x/的三个库更新到最新。 然后修改curveadm库的go.mod ， 使用repalce 替换goph为本地改过代码的目录。 make 后可以使用啦。 @Wine93 麻烦整理下wiki 或者FAQ 。

感谢你的解答，你是否愿意将你的修改以 PR 的方式提交给 curveadm，以便我们合入主分支，并发布最新版本

**Comment by caoxianfei1** [comment]
Close the issue because no reply for a long time.
